//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public int Scope { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int ReviewTypeId { get; set; }
        public string FileName { get; set; }
        public string FileVersion { get; set; }
        public int AssignedTo { get; set; }
        public int ReviewedBy { get; set; }
        public string ReviewerComment { get; set; }
        public string OwnerResponse { get; set; }
        public int SeverityId { get; set; }
        public int CategoryId { get; set; }
        public int StatusId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ReviewType ReviewType { get; set; }
        public virtual Scope Scope1 { get; set; }
        public virtual Severity Severity { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
